<a href="https://colab.research.google.com/github/amira123bd/Generalization_About_Tensors/blob/master/AboutTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

**About Tensors**

Tensors=simply are vectors generalized to a higher dimensions, they are created to store and carry out computations on matrices efficiently

**create tensors**

In [ ]:
string = tf.Variable('hi this is Amira',tf.string)

In [ ]:
print(string.shape)  


()


**Rank/Degree of a tensor**

Rank means = the number of dimensions included

In [ ]:
tf.rank(string) ## rank =0 because simply it is one thing 

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tab=tf.Variable(['hi','hii'],tf.string)
tf.rank(tab) ## 1D 

<tf.Tensor: shape=(), dtype=int32, numpy=1>

**Shape**

Amount of elements in our tensor

In [ ]:
tab.shape

TensorShape([2])

**Reshaping**

In [ ]:
tensor1=tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [ ]:
tensor1=tf.reshape(tensor1,[2,3,1])
print(tensor1)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [ ]:
tensor1=tf.reshape(tensor1,[3,-1])##-1: means you have to infer (3*2*1=6 ==> [3,2])

In [ ]:
print(tensor1)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**types of tensors**

*   Variable ==> the only one that can be changed during execution

*   Constant
*   Placeholder
*   SparseTensor

